services:
  - type: web
    name: cogitate
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cogitate.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
